version: "3.9"
services:
  db:
    image: postgres
    ports:
      - "${DB_PORT}:5433"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}